name: run my Cypress examples
on: [push]
jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: run cypress tests
          uses: cypress-io/github-action@v2
          timeout-minutes: 10
        # with:
        #   record: true
        #   start: npm run serve
        #   wait-on: "http://localhost:8080"
        #   browser: chrome
        # env:
        #   # pass the Dashboard record key as an environment variable
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
